apiVersion: v1
kind: Service
metadata:
  name: user-service 
  namespace: dev
spec:
  selector:
    app: user-service 
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001  # Choisis un port entre 30000 et 32767 
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: mohamedlouay/pfe-user-service:latest  # Remplacez par votre image Docker
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-service.dev.svc.cluster.local:27017/users_db"
